Resources:
  SiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mine-sweeper-site-assets
  cloudfrontDistribution:
    DependsOn: SiteS3Bucket
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ViewerProtocolPolicy: allow-all
          TargetOriginId:  !Ref SiteS3Bucket
          ForwardedValues:
            QueryString: false
        Origins:
        - DomainName: mine-sweeper-site-assets.s3.amazonaws.com
          Id:  !Ref SiteS3Bucket
          OriginAccessControlId:  !Ref cloudforntOriginAccessControl
          S3OriginConfig:
            OriginAccessIdentity: ''
        Enabled: true
  cloudforntOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: ''
        Name:
          !Join
            - ''
            - - 'OAC for '
              - minesweeper
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  bucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:  !Ref SiteS3Bucket
      PolicyDocument:
        Version: '2008-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
        - Sid: AllowCloudFrontServicePrincipal
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Action: s3:GetObject
          Resource: arn:aws:s3:::mine-sweeper-site-assets/*
          Condition:
            StringEquals:
              AWS:SourceArn:
                !Join
                  - ''
                  - - 'arn:aws:cloudfront::'
                    - !Ref AWS::AccountId
                    - ":distribution/"
                    - !Ref cloudfrontDistribution
