Parameters:
  BucketName:
    Type : String
    Description : Name for S3 bucket
  ProjectName:
    Type : String
    Description : Name for project for tagging


Resources:
  SiteS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Ref BucketName
      Tags : 
        - Key: Project
          Value: !Ref ProjectName
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ViewerProtocolPolicy: allow-all
          TargetOriginId:  !Ref SiteS3Bucket
          ForwardedValues:
            QueryString: false
        Origins:
        - DomainName: 
            !Join
              - ''
              - - !Ref BucketName
                - '.s3.amazonaws.com'        
          Id:  !Ref SiteS3Bucket
          OriginAccessControlId:  !Ref cloudforntOriginAccessControl
          S3OriginConfig:
            OriginAccessIdentity: ''
        Enabled: true
      Tags : 
        - Key: Project
          Value: !Ref ProjectName
  cloudforntOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: ''
        Name:
          !Join
            - ''
            - - 'OAC for '
              - !Ref SiteS3Bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  bucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:  !Ref SiteS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: PolicyForCloudFrontPrivateContent
        Statement:
        - Sid: AllowCloudFrontServicePrincipal
          Effect: Allow
          Principal:
            Service: cloudfront.amazonaws.com
          Action: s3:GetObject
          Resource:
            !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BucketName
                - '/*'
          Condition:
            StringEquals:
              AWS:SourceArn:
                !Join
                  - ''
                  - - 'arn:aws:cloudfront::'
                    - !Ref AWS::AccountId
                    - ":distribution/"
                    - !Ref cloudfrontDistribution
