# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  
on:
  push:
    branches: [ "main" , "actionsTesting"]
  pull_request:
    branches: [ "main" , "actionsTesting"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Find location
      run: ls
    - name: change location 
      run: cd ./Website/mine-sweeper-v2
    - name: Find location 2
      run: ls
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Insall
      run: npm ci
    - name: Build
      run: npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: find location
      run: ls
    - name: cf deploy
      run: aws cloudformation deploy --template-file cloudformation\template.yaml --stack-name "mine-sweeper" --parameter-overrides BucketName="mine-sweeper-site-assets" ProjectName="Mine-Sweeper"
    - name: Deploy
      run:  aws s3 cp Website/mine-sweeper-v2 s3://mine-sweeper-site-assets/ --recursive


