# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  
on:
  push:
    branches: [ "main" , "actionsTesting"]
  pull_request:
    branches: [ "main" , "actionsTesting"]

jobs:
  locationTest:
    runs-on: ubuntu-latest
    steps:
    - name: find location
      run: ls
    - name: find location 2
      working-directory:  ../
      run: ls
    - name: find location 3
      working-directory:  ../
      run: pwd
    - name: find location 4
      working-directory:  ./Website
      run: ls
    - name: find location 5
      working-directory:  ./Website
      run: pwd
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: cf deploy
      working-directory:  cloudformation
      run: aws cloudformation deploy --template-file template.yaml --stack-name "mine-sweeper" --parameter-overrides BucketName="mine-sweeper-site-assets" ProjectName="Mine-Sweeper"
    
    - name: Deploy
      run:  aws s3 cp Website/mine-sweeper-v2 s3://mine-sweeper-site-assets/ --recursive


