# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  CI: false
  
on:
  push:
    branches: [ "main" , "actionsTesting"]
  pull_request:
    branches: [ "main" , "actionsTesting"]

jobs:
  locationTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: find location
      run: ls
    - name: find location2
      working-directory:  Website
      run: ls
    - name: find location 5
      working-directory:  Website
      run: pwd
    - name: find location 6
      working-directory: Website/mine-sweeper-v2
      run: ls    
    - name: find location 7
      working-directory: Website/mine-sweeper-v2/public
      run: ls
    - name: find location 8
      working-directory: Website/mine-sweeper-v2/src
      run: ls
  build:
    artifacts:
      untracked: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: Insall
      working-directory: Website/mine-sweeper-v2
      run: npm ci

    - name: Build
      working-directory: Website/mine-sweeper-v2
      run: npm run build




  deploy:
    dependencies:
      - build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true

    - name: cf deploy
      working-directory:  cloudformation
      run: aws cloudformation deploy --template-file template.yaml --stack-name "mine-sweeper" --parameter-overrides BucketName="mine-sweeper-site-assets" ProjectName="Mine-Sweeper"
    
    - name: Deploy
      run:  aws s3 cp Website/mine-sweeper-v2/build s3://mine-sweeper-site-assets/ --recursive


